version: '3'
services:
  main:
    image: mlopscurriculum/api:v0.0
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - local-db
  local-db:
    image: library/mysql:8
    container_name: local-db
    volumes:
        - ./init.sql:/data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test