version: "3.9"
services:
  local-db:
    image: library/mysql:8
    container_name: local-db
    volumes:
        - ./init.sql:/data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    networks:
      - webnet
  main:
    image: mlopscurriculum/api:v0.0
    container_name: mlops-api
    build: .
    ports:
      - 3000:3000
    links:
      - local-db:local-db
    depends_on:
      - local-db
    networks:
      - webnet
networks:
  webnet: